CREATE TABLE "Images" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"location"	TEXT NOT NULL UNIQUE,
	"title"	INTEGER UNIQUE,
	"uploader"	INTEGER NOT NULL,
	FOREIGN KEY ("uploader") REFERENCES Persons(id)
)

CREATE TABLE "Persons" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE
)